name: "Bun Upgrade GitHub Action"
description: "automatically update your dependencies using bun"
inputs:
  IGNORED_DEPENDENCIES:
    description: "dependencies to ignore"
    required: false
  PACKAGE_JSON_PATH:
    description: "path to package.json if not in root directory"
    required: false
  GITHUB_REPOSITORY:
    description: "The GitHub repository - needed for creating and logging urls"
    required: false
    default: ${{ github.repository }}
  GH_TOKEN:
    description: "The GitHub token to use for interacting with the GitHub API"
    required: false
    default: ${{ github.token }}
runs:
  using: "node20"
  main: "./dist/index.js"
branding:
  color: "yellow"
  icon: "package"
